services:
  - type: web
    name: form-validation
    env: node
    buildCommand: npm install && npm run build
    startCommand: node server/server.js
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://teamproject440:MksFdhU1dzYKQeQL@cluster1.jopyiko.mongodb.net/Form_validation?retryWrites=true&w=majority&appName=Cluster1
      - key: PORT
        value: "5000"
